
%%{init: {'theme':'forest'}}%%

sequenceDiagram

    Title Sequence diagram of .main() of /src/gtp/pipelines/preprocess.py

    participant p1 as main()<br>:pipelines/preprocess.py/preprocess.py
    participant p2 as <br>:configs/loaders.py/loaders.py
    participant p3 as <br>:pipelines/preprocess.py/preprocess.py
    participant p4 as <br>:dataloading/path_collectors.py/path_collectors.py
    participant p5 as preprocessor<br>:dataloading/data_preprocessors.py/DataPreprocessor


	p1 ->>+ p2: 1: load_configs(configs)
	p2 -->>- p1: 1: return value
	p1 ->>+ p3: 2: preprocess_phenotypes(cfgs, verbose)
	p3 ->>+ p4: 2.1: get_raw_phenotype_input_directory(configs.io)
	p4 ->>+ p4: 2.1.1: _select_override_if_exists(io_cfgs.default_root, io_cfgs.<br>raw_data_input.root)
	p4 -->>- p4: 2.1.1: return value
	p4 -->>- p3: 2.1: return value
	p3 ->>+ p4: 2.2: get_post_processed_phenotype_directory(configs.io)
	p4 ->>+ p4: 2.2.1: _select_override_if_exists( io_cfgs.default_root,<br>io_cfgs.data_post_process.root<br> )
	p4 -->>- p4: 2.2.1: return value
	p4 -->>- p3: 2.2: return value
	p3 ->>+ p5: 2.3: process(pca_csv_path_suffix=suffix_path)
	p5 ->>+ p5: 2.3.1: _process(*args, **kwargs)
	p5 -->>- p5: 2.3.1: return value
	p5 -->>- p3: 2.3: return value
	p3 ->>+ p5: 2.4: save_result(f"{species}_{wing}_{phenotype}")
	p5 ->>+ p5: 2.4.1: _save_result(os.path.join(self.output_dir,<br>output_suffix))
	p5 -->>- p5: 2.4.1: return value
	p5 -->>- p3: 2.4: return value
	p3 -->>- p1: 2: return value
	p1 ->>+ p3: 3: preprocess_genotypes(cfgs, force_reprocess, num_processes,<br>verbose)
	p3 ->>+ p4: 3.1: get_raw_genotype_input_directory(configs.io)
	p4 ->>+ p4: 3.1.1: _select_override_if_exists(io_cfgs.default_root, io_cfgs.<br>raw_data_input.root)
	p4 -->>- p4: 3.1.1: return value
	p4 -->>- p3: 3.1: return value
	p3 ->>+ p4: 3.2: get_post_processed_genotype_directory(configs.io)
	p4 ->>+ p4: 3.2.1: _select_override_if_exists( io_cfgs.default_root,<br>io_cfgs.data_post_process.root<br> )
	p4 -->>- p4: 3.2.1: return value
	p4 -->>- p3: 3.2: return value
	p3 -->>- p1: 3: return value
        