io: # input / output configurations
    default_root: "/local/scratch/carlyn.1/" # Default root. Used if any 'root' option is null under the 'io' config 
    raw_data_input: # for the raw data directly downloaded
        root: null
        genotype: "dna/vcfs"
        phenotype: "dna/colors"
    data_post_process: # where post processed raw data will be
        root: null
        genotype: "dna/processed/genotypes"
        phenotype: "dna/processed/phenotypes"
global_butterfly_metadata:
    species: ["erato", "melpomene"]
    wings: ["forewings", "hindwings"]
    phenotypes: ["color_1", "color_2", "color_3", "total"]
experiment:
    genotype_scope: "genome" # Either 'genome', 'chromosomes', 'genes'
dev:
    tmp: "tmp"
