# Erato Forewing all colors (10 dimensions)

python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Herato1001_wntA_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Herato1001_wntA_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/erato_forewings_PCA/PCA_color_1_loadings.csv --exp_name Herato1001_wntA_forewings_color1 
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Herato1001_wntA_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Herato1001_wntA_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/erato_forewings_PCA/PCA_color_2_loadings.csv --exp_name Herato1001_wntA_forewings_color2
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Herato1001_wntA_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Herato1001_wntA_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/erato_forewings_PCA/PCA_color_3_loadings.csv --exp_name Herato1001_wntA_forewings_color3

python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Herato1003_elf1a_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Herato1003_elf1a_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/erato_forewings_PCA/PCA_color_1_loadings.csv --exp_name Herato1003_elf1a_forewings_color1 
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Herato1003_elf1a_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Herato1003_elf1a_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/erato_forewings_PCA/PCA_color_2_loadings.csv --exp_name Herato1003_elf1a_forewings_color2
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Herato1003_elf1a_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Herato1003_elf1a_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/erato_forewings_PCA/PCA_color_3_loadings.csv --exp_name Herato1003_elf1a_forewings_color3

python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Herato1301_vvl_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Herato1301_vvl_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/erato_forewings_PCA/PCA_color_1_loadings.csv --exp_name Herato1301_vvl_forewings_color1 
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Herato1301_vvl_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Herato1301_vvl_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/erato_forewings_PCA/PCA_color_2_loadings.csv --exp_name Herato1301_vvl_forewings_color2
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Herato1301_vvl_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Herato1301_vvl_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/erato_forewings_PCA/PCA_color_3_loadings.csv --exp_name Herato1301_vvl_forewings_color3

python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Herato1505_cortex_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Herato1505_cortex_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/erato_forewings_PCA/PCA_color_1_loadings.csv --exp_name Herato1505_cortex_forewings_color1 
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Herato1505_cortex_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Herato1505_cortex_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/erato_forewings_PCA/PCA_color_2_loadings.csv --exp_name Herato1505_cortex_forewings_color2
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Herato1505_cortex_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Herato1505_cortex_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/erato_forewings_PCA/PCA_color_3_loadings.csv --exp_name Herato1505_cortex_forewings_color3

python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Herato1801_optix_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Herato1801_optix_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/erato_forewings_PCA/PCA_color_1_loadings.csv --exp_name Herato1801_optix_forewings_color1 
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Herato1801_optix_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Herato1801_optix_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/erato_forewings_PCA/PCA_color_2_loadings.csv --exp_name Herato1801_optix_forewings_color2
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Herato1801_optix_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Herato1801_optix_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/erato_forewings_PCA/PCA_color_3_loadings.csv --exp_name Herato1801_optix_forewings_color3