# Melpomene Forewing all colors (10 dimensions)

python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Hmel210001o_wntA_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Hmel210001o_wntA_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/melpomene_forewings_PCA/PCA_color_1_loadings.csv --exp_name Hmel210001o_wntA_forewings_color1 
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Hmel210001o_wntA_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Hmel210001o_wntA_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/melpomene_forewings_PCA/PCA_color_2_loadings.csv --exp_name Hmel210001o_wntA_forewings_color2
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Hmel210001o_wntA_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Hmel210001o_wntA_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/melpomene_forewings_PCA/PCA_color_3_loadings.csv --exp_name Hmel210001o_wntA_forewings_color3

python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Hmel210001o_elf1a_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Hmel210001o_elf1a_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/melpomene_forewings_PCA/PCA_color_1_loadings.csv --exp_name Hmel210001o_elf1a_forewings_color1 
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Hmel210001o_elf1a_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Hmel210001o_elf1a_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/melpomene_forewings_PCA/PCA_color_2_loadings.csv --exp_name Hmel210001o_elf1a_forewings_color2
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Hmel210001o_elf1a_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Hmel210001o_elf1a_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/melpomene_forewings_PCA/PCA_color_3_loadings.csv --exp_name Hmel210001o_elf1a_forewings_color3

python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Hmel213001o_vvl_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Hmel213001o_vvl_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/melpomene_forewings_PCA/PCA_color_1_loadings.csv --exp_name Hmel213001o_vvl_forewings_color1 
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Hmel213001o_vvl_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Hmel213001o_vvl_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/melpomene_forewings_PCA/PCA_color_2_loadings.csv --exp_name Hmel213001o_vvl_forewings_color2
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Hmel213001o_vvl_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Hmel213001o_vvl_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/melpomene_forewings_PCA/PCA_color_3_loadings.csv --exp_name Hmel213001o_vvl_forewings_color3

python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Hmel215003o_cortex_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Hmel215003o_cortex_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/melpomene_forewings_PCA/PCA_color_1_loadings.csv --exp_name Hmel215003o_cortex_forewings_color1 
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Hmel215003o_cortex_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Hmel215003o_cortex_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/melpomene_forewings_PCA/PCA_color_2_loadings.csv --exp_name Hmel215003o_cortex_forewings_color2
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Hmel215003o_cortex_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Hmel215003o_cortex_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/melpomene_forewings_PCA/PCA_color_3_loadings.csv --exp_name Hmel215003o_cortex_forewings_color3

python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Hmel218003o_optix_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Hmel218003o_optix_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/melpomene_forewings_PCA/PCA_color_1_loadings.csv --exp_name Hmel218003o_optix_forewings_color1 
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Hmel218003o_optix_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Hmel218003o_optix_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/melpomene_forewings_PCA/PCA_color_2_loadings.csv --exp_name Hmel218003o_optix_forewings_color2
python train.py --epochs 200 --out_dims=50 --input_data /local/scratch/carlyn.1/dna/vcfs/Hmel218003o_optix_vcfs.npz --input_metadata /local/scratch/carlyn.1/dna/vcfs/Hmel218003o_optix_names.json --pca_loadings /local/scratch/carlyn.1/dna/colors/melpomene_forewings_PCA/PCA_color_3_loadings.csv --exp_name Hmel218003o_optix_forewings_color3