python -m gtp.train_whole_genome --chromosome 1 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 2 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 3 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 4 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 5 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 6 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 7 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 8 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 9 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 10 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 11 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 12 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 13 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 14 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 15 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 16 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 17 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 18 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 19 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 20 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
python -m gtp.train_whole_genome --chromosome 21 --species erato --color color_1 --wing forewings --epochs 100 --batch_size 32 --exp_name whole_genome
